### ISSUE TITLE
theremin_sintable3.c: No such file or directory

### ISSUE THREAD

**Issue by RebeccaCotton** [GaudiLabs/OpenTheremin_V3#1]
Hi Urs, 

I just got the Theremin, and have a problem. Hope you can help! :-) Best, Rebecca

**Installing the Open Theremin Package V3 does not work.**

Steps to reproduce:

1. download open theremin zip from git hub
2. connect Arduino
3. open aduino web IDE
4. write test package on arduino: works!
5. upload theremin sketch to IDE
6. deploy to arduino

Result: fails with the following message:

> /tmp/706839763/build/sketch/ihandlers.cpp:11:32: fatal error: theremin_sintable3.c: No such file or directory

The whole output from the install:
> /home/builder/opt/arduino-builder/arduino-builder -compile -core-api-version 10611 -hardware /home/builder/opt/arduino-builder/hardware -hardware /home/builder/.arduino15/packages -tools /home/builder/opt/arduino-builder/tools -tools /home/builder/.arduino15/packages -built-in-libraries /home/builder/opt/libraries/latest -logger humantags -fqbn arduino:avr:uno -build-cache /tmp -build-path /tmp/706839763/build -verbose -prefs runtime.tools.i586-poky-linux-uclibc.path=/home/builder/.arduino15/packages/Intel/tools/i586-poky-linux-uclibc/1.6.2+1.0 -prefs runtime.tools.CMSIS.path=/home/builder/.arduino15/packages/arduino/tools/CMSIS/4.5.0 -prefs runtime.tools.esptool.path=/home/builder/.arduino15/packages/esp8266/tools/esptool/2.5.0-3-20ed2b9 -prefs runtime.tools.arc-elf32.path=/home/builder/.arduino15/packages/Intel/tools/arc-elf32/1.6.9+1.0.1 -prefs runtime.tools.flashpack.path=/home/builder/.arduino15/packages/Intel/tools/flashpack/2.0.0 -prefs runtime.tools.avr-gcc.path=/home/builder/.arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2 -prefs runtime.tools.dfu-util.path=/home/builder/.arduino15/packages/arduino/tools/dfu-util/0.9.0-arduino1 -prefs runtime.tools.bossac.path=/home/builder/.arduino15/packages/industruino/tools/bossac/1.7.0-industruino -prefs runtime.tools.nrf5x-cl-tools.path=/home/builder/.arduino15/packages/arduino/tools/nrf5x-cl-tools/9.3.1 -prefs runtime.tools.mkspiffs.path=/home/builder/.arduino15/packages/esp8266/tools/mkspiffs/2.5.0-3-20ed2b9 -prefs runtime.tools.xtensa-lx106-elf-gcc.path=/home/builder/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-3-20ed2b9 -prefs runtime.tools.arduino101load.path=/home/builder/.arduino15/packages/Intel/tools/arduino101load/2.0.1 -prefs runtime.tools.arduinoOTA.path=/home/builder/.arduino15/packages/arduino/tools/arduinoOTA/1.2.1 -prefs runtime.tools.x86-linux-gcc.path=/home/builder/.arduino15/packages/arduino/tools/x86-linux-gcc/7.2.0 -prefs runtime.tools.openocd.path=/home/builder/.arduino15/packages/arduino/tools/openocd/0.10.0-arduino9 -prefs runtime.tools.sketchUploader.path=/home/builder/.arduino15/packages/Intel/tools/sketchUploader/1.6.2+1.0 -prefs runtime.tools.core2-32-poky-linux.path=/home/builder/.arduino15/packages/Intel/tools/core2-32-poky-linux/1.6.2+1.0 -prefs runtime.tools.linuxuploader.path=/home/builder/.arduino15/packages/arduino/tools/linuxuploader/1.5.1 -prefs runtime.tools.arm-linux-gcc.path=/home/builder/.arduino15/packages/arduino/tools/arm-linux-gcc/4.9.3 -prefs runtime.tools.arm-none-eabi-gcc.path=/home/builder/.arduino15/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4 -prefs runtime.tools.avrdude.path=/home/builder/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino14 -prefs runtime.tools.CMSIS-Atmel.path=/home/builder/.arduino15/packages/arduino/tools/CMSIS-Atmel/1.2.0 -libraries /tmp/706839763/custom -libraries /tmp/706839763/pinned /tmp/706839763/Open_Theremin_V3

> Multiple libraries were found for "timer.h"

> Used: /home/builder/opt/libraries/latest/arduino_timer_1_0_0

> Not used: /home/builder/opt/libraries/latest/embedded_template_library_10_21_2

> Using library arduino_timer_1_0_0 at version 1.0.0 in folder: /home/builder/opt/libraries/latest/arduino_timer_1_0_0

> /tmp/706839763/build/sketch/ihandlers.cpp:11:32: fatal error: theremin_sintable3.c: No such file or directory

> compilation terminated.

> exit status 1

Environment: Suse Linux with a current version of Firefox

**Comment by GaudiLabs** [comment]
Hi

You need to download the. zip file from the link in the instruction. Then unpack the. zip file. From the extracted folder open the. ino file from the Arduino IDE. Then you should be able to upload it.

Best,
Urs

On 13 September 2019 20:52:30 CEST, Rebecca <notifications@github.com> wrote:
>Hi Urs, 
>
>I just got the Theremin, and have a problem. Hope you can help! :-)
>Best, Rebecca
>
>**Installing the Open Theremin Package V3 does not work.**
>
>Steps to reproduce:
>
>1. download open theremin zip from git hub
>2. connect Arduino
>3. open aduino web IDE
>4. write test package on arduino: works!
>5. upload theremin sketch to IDE
>6. deploy to arduino
>
>Result: fails with the following message:
>
>> /tmp/706839763/build/sketch/ihandlers.cpp:11:32: fatal error:
>theremin_sintable3.c: No such file or directory
>
>The whole output from the install:
>> /home/builder/opt/arduino-builder/arduino-builder -compile
>-core-api-version 10611 -hardware
>/home/builder/opt/arduino-builder/hardware -hardware
>/home/builder/.arduino15/packages -tools
>/home/builder/opt/arduino-builder/tools -tools
>/home/builder/.arduino15/packages -built-in-libraries
>/home/builder/opt/libraries/latest -logger humantags -fqbn
>arduino:avr:uno -build-cache /tmp -build-path /tmp/706839763/build
>-verbose -prefs
>runtime.tools.i586-poky-linux-uclibc.path=/home/builder/.arduino15/packages/Intel/tools/i586-poky-linux-uclibc/1.6.2+1.0
>-prefs
>runtime.tools.CMSIS.path=/home/builder/.arduino15/packages/arduino/tools/CMSIS/4.5.0
>-prefs
>runtime.tools.esptool.path=/home/builder/.arduino15/packages/esp8266/tools/esptool/2.5.0-3-20ed2b9
>-prefs
>runtime.tools.arc-elf32.path=/home/builder/.arduino15/packages/Intel/tools/arc-elf32/1.6.9+1.0.1
>-prefs
>runtime.tools.flashpack.path=/home/builder/.arduino15/packages/Intel/tools/flashpack/2.0.0
>-prefs
>runtime.tools.avr-gcc.path=/home/builder/.arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2
>-prefs
>runtime.tools.dfu-util.path=/home/builder/.arduino15/packages/arduino/tools/dfu-util/0.9.0-arduino1
>-prefs
>runtime.tools.bossac.path=/home/builder/.arduino15/packages/industruino/tools/bossac/1.7.0-industruino
>-prefs
>runtime.tools.nrf5x-cl-tools.path=/home/builder/.arduino15/packages/arduino/tools/nrf5x-cl-tools/9.3.1
>-prefs
>runtime.tools.mkspiffs.path=/home/builder/.arduino15/packages/esp8266/tools/mkspiffs/2.5.0-3-20ed2b9
>-prefs
>runtime.tools.xtensa-lx106-elf-gcc.path=/home/builder/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-3-20ed2b9
>-prefs
>runtime.tools.arduino101load.path=/home/builder/.arduino15/packages/Intel/tools/arduino101load/2.0.1
>-prefs
>runtime.tools.arduinoOTA.path=/home/builder/.arduino15/packages/arduino/tools/arduinoOTA/1.2.1
>-prefs
>runtime.tools.x86-linux-gcc.path=/home/builder/.arduino15/packages/arduino/tools/x86-linux-gcc/7.2.0
>-prefs
>runtime.tools.openocd.path=/home/builder/.arduino15/packages/arduino/tools/openocd/0.10.0-arduino9
>-prefs
>runtime.tools.sketchUploader.path=/home/builder/.arduino15/packages/Intel/tools/sketchUploader/1.6.2+1.0
>-prefs
>runtime.tools.core2-32-poky-linux.path=/home/builder/.arduino15/packages/Intel/tools/core2-32-poky-linux/1.6.2+1.0
>-prefs
>runtime.tools.linuxuploader.path=/home/builder/.arduino15/packages/arduino/tools/linuxuploader/1.5.1
>-prefs
>runtime.tools.arm-linux-gcc.path=/home/builder/.arduino15/packages/arduino/tools/arm-linux-gcc/4.9.3
>-prefs
>runtime.tools.arm-none-eabi-gcc.path=/home/builder/.arduino15/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4
>-prefs
>runtime.tools.avrdude.path=/home/builder/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino14
>-prefs
>runtime.tools.CMSIS-Atmel.path=/home/builder/.arduino15/packages/arduino/tools/CMSIS-Atmel/1.2.0
>-libraries /tmp/706839763/custom -libraries /tmp/706839763/pinned
>/tmp/706839763/Open_Theremin_V3
>
>> Multiple libraries were found for "timer.h"
>
>> Used: /home/builder/opt/libraries/latest/arduino_timer_1_0_0
>
>> Not used:
>/home/builder/opt/libraries/latest/embedded_template_library_10_21_2
>
>> Using library arduino_timer_1_0_0 at version 1.0.0 in folder:
>/home/builder/opt/libraries/latest/arduino_timer_1_0_0
>
>> /tmp/706839763/build/sketch/ihandlers.cpp:11:32: fatal error:
>theremin_sintable3.c: No such file or directory
>
>> compilation terminated.
>
>> exit status 1
>
>Environment: Suse Linux with a current version of Firefox
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/GaudiLabs/OpenTheremin_V3/issues/1

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by RebeccaCotton** [comment]
Hi Urs, thank you for the quick answer.
I found the issue. Which was that for some reason the Arduino IDE did not import the zipped sketch correctly, and some of the files where missing.
I added them manually to the sketch and it worked.

Thank you!
