### ISSUE TITLE
Auto-Calibration Not Working

### ISSUE THREAD

**Issue by sportsdrink** [GaudiLabs/OpenTheremin_V3#11]
I am unable to calibrate the theremin with the Function button. I don't see any feedback on the device when I hold the button down for more than 2 seconds. Since my soldering skills are poor, I went back and tried to re-solder the connections to see if that would help, but no luck. Not sure if there are pins I didn't solder correctly either that affect the Function knob, but everything else seems to be okay. 

Thank you in advance for your assistance.

**Comment by Theremingenieur** [comment]
After pressing the fonction button for 2-3 seconds, the Theremin should emit the calibration sound (suite of 3 ascending tones).

Did you check the voltage level on PD6 of the Arduino towards GND? Without the button pressed, it should be +5V, and go down to 0V while the button is pressed (see schematics on Gaudi.ch)

**Comment by Cultura-Difusa** [comment]
I have the same problem. I have checked the voltage thing (4.82v), when pressed goes to 0... yet when pressed for 2/3 seconds no sound or yellow led showing calibration. Any ideas? (Btw, this is my second v3 theremin, I had no problems with de first).

**Comment by GaudiLabs** [comment]
Must be a soldering issue. Check with the soldering quality chart here: http://gaudi.ch/OpenTheremin/index.php/home/notes?id=192 
And see instructions here for instructions on soldering: https://mightyohm.com/files/soldercomic/FullSolderComic_EN.pdf

Issue closed, not a software issue.
