### ISSUE TITLE
Troubleshooting help

### ISSUE THREAD

**Issue by CGW94** [GaudiLabs/OpenTheremin_V3#9]
Hi there,

Not sure if you still check this or not. I recently finished putting together your board!

I plugged it in and the red LED comes on and thats it :( 

I am very confident that i screwed something up but im just not sure what.

Anywhere you could suggest that I start looking? Just trying to get into calibration mode

**Comment by GaudiLabs** [comment]
Hi 
Did you check you soldering? You can send me a picture of front and back of your board to info@gaudi.ch and I will check.

Best,
Urs
